packages:
  - apps/*
  - components/*
  - configs/*
  - packages/*
  - primitives/*

catalog:
  "@vanilla-extract/css": "1.21.2"
  "@vanilla-extract/recipes": "0.5.7"
  "@vanilla-extract/rollup-plugin": "1.5.4"
  clsx: "2.1.1"

allowBuilds:
  '@swc/core': true
  esbuild: true
  sharp: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@wondocs/core@0.1.0-beta.5'
  - '@wondocs/next-plugin@0.1.0-beta.5'
