sonar.projectKey=wonwon0307_design
sonar.organization=wonwon0307

sonar.sources=apps,components,configs,foundations,packages

sonar.typescript.tsconfigPaths=**/*/tsconfig.json

sonar.exclusions=**/node_modules/**,**/dist/**
sonar.coverage.exclusions=**/*.*
sonar.cpd.exclusions=**/tests/**
