import { applyTokens } from "@/utils/apply-tokens";
import { buildCssVariables } from "@/utils/css-variables";

const STYLE_TAG_ID = "wondesign-tokens";

function getStyleTag(): HTMLStyleElement | null {
  return document.getElementById(STYLE_TAG_ID) as HTMLStyleElement | null;
}

afterEach(() => {
  getStyleTag()?.remove();
});

describe("applyTokens", () => {
  it("creates a style tag in document.head with the correct id", () => {
    applyTokens();
    const style = getStyleTag();
    expect(style).not.toBeNull();
    expect(style?.tagName).toBe("STYLE");
    expect(document.head.contains(style)).toBe(true);
  });

  it("sets style tag content to the CSS generated by buildCssVariables", () => {
    applyTokens();
    const style = getStyleTag();
    const expected = buildCssVariables({}, ":root");
    expect(style?.textContent).toBe(expected);
  });

  it("reuses the existing style tag on subsequent calls", () => {
    applyTokens();
    applyTokens();
    const tags = document.head.querySelectorAll(`#${STYLE_TAG_ID}`);
    expect(tags.length).toBe(1);
  });

  it("replaces content when called again with a different theme", () => {
    applyTokens();
    const first = getStyleTag()?.textContent;
    applyTokens({
      radius: {
        xs: "99px",
        sm: "99px",
        md: "99px",
        lg: "99px",
        xl: "99px",
        full: "9999px",
      },
    });
    const second = getStyleTag()?.textContent;
    expect(second).not.toBe(first);
    expect(second).toContain("99px");
  });

  it("uses a custom selector when provided", () => {
    applyTokens({}, ".dark");
    const style = getStyleTag();
    expect(style?.textContent).toContain(".dark {");
    expect(style?.textContent).not.toContain(":root {");
  });

  it("defaults to :root selector when none is provided", () => {
    applyTokens();
    expect(getStyleTag()?.textContent).toContain(":root {");
  });
});
